language: node_js

dist: trusty
sudo: required

compiler: gcc

before_install:
 - pwd
 - sudo apt-get -qq update
 - sudo apt-get install -y build-essential npm
 - cd /home/travis/build/mjoppich/igem_munich_2018


before_script:
 - npm install

script: npm run build
